### ISSUE TITLE
"Not found" is shown without 404 in fixed page. If turn off Bogo, the page is re-appeared but web design is broken.

### ISSUE THREAD

**Issue by Anshin83** [takayukister/bogo#198]
![not found](https://user-images.githubusercontent.com/98157847/150514343-109967b2-f834-4f18-85ab-fba2ba5ffe8d.png)

I have no idea which point is wrong, I can open other language page but only main page (Homepage) have problem.
could you advise how should I fix this matter? @takayukister  
https://anshin-bersih.com/

**Comment by takayukister** [comment]
**Warning:** GitHub isn't a place to post your support requests. Any support requests posted here will be closed without explanation. If you do it more than once, you will get blocked automatically.
