### ISSUE TITLE
Change "Punjabi" to "Panjabi"

### ISSUE THREAD

**Issue by takayukister** [takayukister/bogo#72]
See https://make.wordpress.org/polyglots/2020/03/26/the-language-name-in-english/

In includes/functions.php we have "Punjabi" now. If the name is changed in https://translate.wordpress.org/ then we will change it as well.

**Comment by itpixelz** [comment]
@takayukister the correct spellings are Punjabi, see here https://en.wikipedia.org/wiki/Punjabi_language

**Comment by takayukister** [comment]
So, Punjabi and Panjabi are both correct? Hmm. Let's wait and see until the Polyglots team makes a judgment.

**Comment by itpixelz** [comment]
Yes I agree with you, I have added my comment in the thread on WP too, let see :)

**Comment by ranapunjabi** [comment]
There are two languages Punjabi/Panjabi. One is used in Pakistan and other one in India.
In Pakistan it is written in perso-arabic script and India in Gurumukhi script.
And the name of Indian Language (in gurmukhi script) is Panjabi (pan).
The name of Pakistani language (in arabic script) is Punjabi (pnb).
So, here already added Punjabi is in gurmukhi, kindly rename to Panjabi, and also add perso-arabic scriptted Punjabi language as name of Punjabi.
Also see here, the names
Indian language:
https://glosbe.com/pan
https://glosbe.com/pan/en
Pakistani language:
https://glosbe.com/pnb
https://glosbe.com/pnb/en

Thanks and Regards

**Comment by takayukister** [comment]
Thank you for the detailed explanation. We'll wait to see the Polyglots team's official decision on this.
